import { createFileRoute, Link } from "@tanstack/react-router";
import { PublicHeader } from "@/components/public-header";
import { PublicFooter } from "@/components/public-footer";
import { FileText } from "lucide-react";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — OddysAI" },
      { name: "description", content: "OddysAI Terms of Service. Subscription billing, refund policy, AI analysis disclaimer and affiliate program terms for our sports analytics platform." },
      { property: "og:title", content: "Terms of Service — OddysAI" },
      { property: "og:description", content: "Read the Terms of Service for OddysAI, an AI-powered sports analytics platform." },
    ],
  }),
  component: TermsPage,
});

function Section({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-xl font-bold mb-2">{n}. {title}</h2>
      <div className="space-y-3 text-sm text-muted-foreground leading-relaxed">{children}</div>
    </section>
  );
}

function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <PublicHeader />
      <article className="container mx-auto px-4 py-16 max-w-3xl">
        <div className="flex items-center gap-2 mb-3">
          <FileText className="h-5 w-5 text-primary" />
          <span className="text-xs font-mono uppercase tracking-wider text-primary">Legal</span>
        </div>
        <h1 className="font-display text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <p className="text-sm text-muted-foreground leading-relaxed">
          These Terms of Service ("Terms") govern your access to and use of OddysAI ("OddysAI", "we", "our", "us"),
          an AI-powered sports analytics and match analysis platform delivered as a software-as-a-service
          subscription. By creating an account or using the platform you agree to these Terms.
        </p>

        <Section n={1} title="What OddysAI is (and is not)">
          <p>
            OddysAI is an analytics and information service. We use artificial intelligence and statistical
            models to produce probability estimates, match breakdowns, form insights, and bankroll
            calculations. OddysAI is <strong className="text-foreground">not</strong> a bookmaker, sportsbook,
            casino, betting exchange or gambling operator. We do not accept, place, broker, settle or
            facilitate wagers of any kind, and we do not hold customer funds.
          </p>
        </Section>

        <Section n={2} title="Eligibility">
          <p>
            You must be at least 18 years old, or the age of majority in your jurisdiction, whichever is
            higher. You are responsible for ensuring that your use of analytics-based products is lawful in
            your country, state, or region. The service is not directed at jurisdictions where it is
            prohibited, and we may restrict access at our discretion.
          </p>
        </Section>

        <Section n={3} title="Account and security">
          <p>
            You are responsible for keeping your login credentials confidential and for any activity under
            your account. Notify us at <a className="text-primary hover:underline" href="mailto:mail@oddysai.com">mail@oddysai.com</a> immediately if you suspect unauthorised access.
          </p>
        </Section>

        <Section n={4} title="AI analysis disclaimer">
          <p>
            All output produced by OddysAI — including probabilities, confidence scores, suggested stake
            sizes, value-bet flags, written commentary and historical comparisons — is generated by
            statistical and AI models from publicly available data. It is provided
            <strong className="text-foreground"> "as is" for informational and educational purposes only</strong>.
          </p>
          <p>
            AI models can be wrong, outdated, biased, or incomplete. Outputs may contain hallucinated
            facts, stale lineups, mis-priced odds, or arithmetic errors. You must independently verify any
            information before acting on it. OddysAI does not provide investment, financial, tax, legal or
            professional gambling advice.
          </p>
        </Section>

        <Section n={5} title="No guaranteed profits">
          <p>
            Sports outcomes are inherently uncertain. Nothing on OddysAI is a guarantee, prediction of fact,
            or promise of profit. Past performance of any model, tipster, leaderboard, or backtest does
            not predict future results. Any decision to wager money is yours alone and made entirely at
            your own risk. <strong className="text-foreground">You can lose some or all of any money you bet.</strong>
          </p>
        </Section>

        <Section n={6} title="Responsible gambling">
          <p>
            Although OddysAI is not a gambling operator, our analytics may be used by people who choose to
            wager. We strongly encourage responsible behaviour: set deposit and loss limits, never chase
            losses, never bet borrowed money, and take regular breaks. If gambling stops being fun or
            starts causing harm, please seek help — see our <Link to="/responsible-gambling" className="text-primary hover:underline">Responsible Gambling</Link> page for resources including GamCare,
            BeGambleAware and the National Council on Problem Gambling.
          </p>
        </Section>

        <Section n={7} title="Subscriptions and billing">
          <p>
            OddysAI offers free and paid subscription plans. Paid plans are billed on a recurring basis
            (monthly or annually, depending on the plan you choose) at the rate displayed on the
            <Link to="/pricing" className="text-primary hover:underline"> Pricing</Link> page at the time of purchase. Billing is handled by our payment processor.
          </p>
          <p>
            Your subscription renews automatically at the end of each billing cycle unless you cancel
            beforehand. You can cancel at any time from Account Settings; cancellation stops future
            renewals and your paid features remain active until the end of the current period. Prices,
            features and plan tiers may change with reasonable notice; existing paid periods are not
            re-priced.
          </p>
        </Section>

        <Section n={8} title="Refund policy">
          <p>
            Because OddysAI delivers digital services that are consumed in real time, all subscription fees
            are <strong className="text-foreground">non-refundable</strong> once the billing period has
            started, except where required by applicable law (for example a statutory cooling-off right
            for first-time consumers in the EU/UK within 14 days of purchase, provided the service has
            not been substantially used).
          </p>
          <p>
            We may issue a discretionary, pro-rated refund in cases of duplicate charges, prolonged
            service outage, or clear billing error. Refund requests must be sent to
            <a className="text-primary hover:underline" href="mailto:mail@oddysai.com"> mail@oddysai.com</a> within 30 days of the charge.
          </p>
        </Section>

        <Section n={9} title="Affiliate program">
          <p>
            Approved affiliates may earn a recurring commission (default 30%) on the net subscription
            revenue of users they refer, for as long as the referred subscription remains active and paid.
            Commissions accrue monthly and are paid out once the affiliate balance reaches the published
            minimum threshold.
          </p>
          <p>
            Affiliates must promote OddysAI honestly and lawfully. The following are prohibited and result
            in immediate termination and forfeiture of unpaid commissions: self-referrals, incentivised
            traffic, spam, paid search bidding on our trademarks, false claims of guaranteed profit,
            promotion to minors, or marketing in jurisdictions where the service is restricted.
          </p>
        </Section>

        <Section n={10} title="Acceptable use">
          <p>
            You agree not to scrape, resell, redistribute or reverse-engineer the service or its outputs;
            not to use OddysAI to build a competing product; not to share your account; and not to use the
            platform to harass, defraud, or harm others. We may suspend or terminate accounts that breach
            these Terms.
          </p>
        </Section>

        <Section n={11} title="Intellectual property">
          <p>
            OddysAI, the OddysAI logo, the underlying models, code, and the look and feel of the platform are
            owned by us and protected by intellectual property law. We grant you a personal,
            non-transferable, revocable licence to use the service for its intended purpose during an
            active subscription.
          </p>
        </Section>

        <Section n={12} title="Limitation of liability">
          <p>
            To the maximum extent permitted by law, OddysAI is not liable for any indirect, incidental,
            consequential, special or punitive damages, including lost profits, lost wagers, lost
            opportunity, or data loss, arising from your use of the service. Our total aggregate liability
            for any claim is limited to the amount you paid us in the 12 months preceding the claim.
          </p>
        </Section>

        <Section n={13} title="Changes to these Terms">
          <p>
            We may update these Terms from time to time. Material changes will be communicated via email
            or in-app notice at least 14 days before they take effect. Continued use of the service after
            the effective date constitutes acceptance of the updated Terms.
          </p>
        </Section>

        <Section n={14} title="Governing law">
          <p>
            These Terms are governed by the laws of the jurisdiction in which OddysAI is established, without
            regard to conflict-of-laws principles. Disputes will be handled by the competent courts of
            that jurisdiction, subject to any non-waivable consumer rights.
          </p>
        </Section>

        <Section n={15} title="Contact">
          <p>
            Questions about these Terms? Email <a className="text-primary hover:underline" href="mailto:mail@oddysai.com">mail@oddysai.com</a> or visit our <Link to="/contact" className="text-primary hover:underline">Contact page</Link>.
          </p>
        </Section>
      </article>
      <PublicFooter />
    </div>
  );
}
