/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResponsibleGamblingRouteImport } from './routes/responsible-gambling'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeMatchRouteImport } from './routes/api/analyze-match'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppLiveRouteImport } from './routes/_app/live'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppApiSourcesRouteImport } from './routes/_app/api-sources'
import { Route as AppAnalyzerRouteImport } from './routes/_app/analyzer'
import { Route as AppAffiliateRouteImport } from './routes/_app/affiliate'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiPublicQuickPredictionRouteImport } from './routes/api/public/quick-prediction'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicNowpaymentsWebhookRouteImport } from './routes/api/public/nowpayments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleGamblingRoute = ResponsibleGamblingRouteImport.update({
  id: '/responsible-gambling',
  path: '/responsible-gambling',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeMatchRoute = ApiAnalyzeMatchRouteImport.update({
  id: '/api/analyze-match',
  path: '/api/analyze-match',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApiSourcesRoute = AppApiSourcesRouteImport.update({
  id: '/api-sources',
  path: '/api-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyzerRoute = AppAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliateRoute = AppAffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicQuickPredictionRoute =
  ApiPublicQuickPredictionRouteImport.update({
    id: '/api/public/quick-prediction',
    path: '/api/public/quick-prediction',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNowpaymentsWebhookRoute =
  ApiPublicNowpaymentsWebhookRouteImport.update({
    id: '/api/public/nowpayments/webhook',
    path: '/api/public/nowpayments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/affiliate': typeof AppAffiliateRoute
  '/analyzer': typeof AppAnalyzerRoute
  '/api-sources': typeof AppApiSourcesRoute
  '/dashboard': typeof AppDashboardRoute
  '/live': typeof AppLiveRoute
  '/settings': typeof AppSettingsRoute
  '/api/analyze-match': typeof ApiAnalyzeMatchRoute
  '/api/public/quick-prediction': typeof ApiPublicQuickPredictionRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/affiliate': typeof AppAffiliateRoute
  '/analyzer': typeof AppAnalyzerRoute
  '/api-sources': typeof AppApiSourcesRoute
  '/dashboard': typeof AppDashboardRoute
  '/live': typeof AppLiveRoute
  '/settings': typeof AppSettingsRoute
  '/api/analyze-match': typeof ApiAnalyzeMatchRoute
  '/api/public/quick-prediction': typeof ApiPublicQuickPredictionRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/responsible-gambling': typeof ResponsibleGamblingRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/affiliate': typeof AppAffiliateRoute
  '/_app/analyzer': typeof AppAnalyzerRoute
  '/_app/api-sources': typeof AppApiSourcesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/analyze-match': typeof ApiAnalyzeMatchRoute
  '/api/public/quick-prediction': typeof ApiPublicQuickPredictionRoute
  '/api/public/nowpayments/webhook': typeof ApiPublicNowpaymentsWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gambling'
    | '/terms'
    | '/admin'
    | '/affiliate'
    | '/analyzer'
    | '/api-sources'
    | '/dashboard'
    | '/live'
    | '/settings'
    | '/api/analyze-match'
    | '/api/public/quick-prediction'
    | '/api/public/nowpayments/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gambling'
    | '/terms'
    | '/admin'
    | '/affiliate'
    | '/analyzer'
    | '/api-sources'
    | '/dashboard'
    | '/live'
    | '/settings'
    | '/api/analyze-match'
    | '/api/public/quick-prediction'
    | '/api/public/nowpayments/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/responsible-gambling'
    | '/terms'
    | '/_app/admin'
    | '/_app/affiliate'
    | '/_app/analyzer'
    | '/_app/api-sources'
    | '/_app/dashboard'
    | '/_app/live'
    | '/_app/settings'
    | '/api/analyze-match'
    | '/api/public/quick-prediction'
    | '/api/public/nowpayments/webhook'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResponsibleGamblingRoute: typeof ResponsibleGamblingRoute
  TermsRoute: typeof TermsRoute
  ApiAnalyzeMatchRoute: typeof ApiAnalyzeMatchRoute
  ApiPublicQuickPredictionRoute: typeof ApiPublicQuickPredictionRoute
  ApiPublicNowpaymentsWebhookRoute: typeof ApiPublicNowpaymentsWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-gambling': {
      id: '/responsible-gambling'
      path: '/responsible-gambling'
      fullPath: '/responsible-gambling'
      preLoaderRoute: typeof ResponsibleGamblingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-match': {
      id: '/api/analyze-match'
      path: '/api/analyze-match'
      fullPath: '/api/analyze-match'
      preLoaderRoute: typeof ApiAnalyzeMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-sources': {
      id: '/_app/api-sources'
      path: '/api-sources'
      fullPath: '/api-sources'
      preLoaderRoute: typeof AppApiSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyzer': {
      id: '/_app/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AppAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/affiliate': {
      id: '/_app/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AppAffiliateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/quick-prediction': {
      id: '/api/public/quick-prediction'
      path: '/api/public/quick-prediction'
      fullPath: '/api/public/quick-prediction'
      preLoaderRoute: typeof ApiPublicQuickPredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nowpayments/webhook': {
      id: '/api/public/nowpayments/webhook'
      path: '/api/public/nowpayments/webhook'
      fullPath: '/api/public/nowpayments/webhook'
      preLoaderRoute: typeof ApiPublicNowpaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAffiliateRoute: typeof AppAffiliateRoute
  AppAnalyzerRoute: typeof AppAnalyzerRoute
  AppApiSourcesRoute: typeof AppApiSourcesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLiveRoute: typeof AppLiveRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAffiliateRoute: AppAffiliateRoute,
  AppAnalyzerRoute: AppAnalyzerRoute,
  AppApiSourcesRoute: AppApiSourcesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLiveRoute: AppLiveRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResponsibleGamblingRoute: ResponsibleGamblingRoute,
  TermsRoute: TermsRoute,
  ApiAnalyzeMatchRoute: ApiAnalyzeMatchRoute,
  ApiPublicQuickPredictionRoute: ApiPublicQuickPredictionRoute,
  ApiPublicNowpaymentsWebhookRoute: ApiPublicNowpaymentsWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
